"""login_export.py — headed Chromium on Xvfb for a human to sign into YouTube.

Launches a persistent-profile Chromium on the X display, opens YouTube, then
polls until it sees the Google auth cookies (SAPISID + __Secure-1PSID). Once
logged in, it exports every cookie in the context to a Netscape-format
cookies.txt that yt-dlp can use. The human does the typing; this script only
watches and exports.

Usage:  .venv/bin/python login_export.py
"""
import os
import sys
import time

from playwright.sync_api import sync_playwright

OUT = "/home/ubuntu/clipper/cookies.txt"
AUTH_NAMES = {"SAPISID", "SID", "__Secure-1PSID"}


def to_netscape(cookies: list) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# generated by login_export.py (playwright) — do not edit",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires")
        expires = int(expires) if (expires and expires > 0) else 0
        lines.append(
            "\t".join([
                domain,
                include_sub,
                c.get("path", "/"),
                secure,
                str(expires),
                c.get("name", ""),
                c.get("value", ""),
            ])
        )
    return "\n".join(lines) + "\n"


def _launch(p):
    # Anti-automation: Google refuses sign-in from a browser it can fingerprint
    # as driven (navigator.webdriver=true / --enable-automation). Strip both.
    args = [
        "--disable-blink-features=AutomationControlled",
        "--no-sandbox",
        "--no-first-run",
        "--no-default-browser-check",
    ]
    kwargs = dict(
        headless=False,
        args=args,
        ignore_default_args=["--enable-automation"],
    )
    try:
        return p.chromium.launch(**kwargs)
    except Exception:
        return p.chromium.launch(**kwargs)


def main() -> int:
    with sync_playwright() as p:
        browser = _launch(p)
        ctx = browser.new_context(no_viewport=True)
        ctx.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
        )
        page = ctx.new_page()
        try:
            page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=60000)
        except Exception as e:
            print(f"warn: initial nav failed: {e}", flush=True)

        print("READY: browser open on X display — log in via VNC now", flush=True)
        print("(polling for auth cookies; will auto-export when login completes)", flush=True)

        while True:
            time.sleep(3)
            try:
                state = ctx.storage_state()
            except Exception:
                continue
            cookies = state.get("cookies", [])
            names = {c.get("name") for c in cookies}
            if AUTH_NAMES <= names:
                with open(OUT, "w", encoding="utf-8") as f:
                    f.write(to_netscape(cookies))
                print(f"EXPORTED {len(cookies)} cookies -> {OUT}", flush=True)
                break
        time.sleep(2)
        browser.close()
    print("DONE", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
